version: '3.8'

services:
  # ------------------
  # MySQL
  # ------------------
  mysql:
    image: mysql:8.0
    container_name: textok_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123414
      MYSQL_DATABASE: next5_db
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password
    networks:
      - next5-net

  # ------------------
  # Redis
  # ------------------
  redis:
    image: redis:7.2
    container_name: textok_redis
    ports:
      - "6379:6379"
    networks:
      - next5-net

  # ------------------
  # Elasticsearch 8.18.8 + Nori plugin
  # ------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.8
    container_name: textok-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    command: >
      bash -c "
        bin/elasticsearch-plugin install --batch analysis-nori;
        /usr/local/bin/docker-entrypoint.sh elasticsearch
      "
    ports:
      - "9200:9200"
    networks:
      - next5-net

  # ------------------
  # Kibana 8.18.8
  # ------------------
  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.8
    container_name: textok-kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://next5-elasticsearch:9200
    ports:
      - 5601:5601
    profiles: [ "elk" ]
    depends_on:
      - elasticsearch
    networks:
      - next5-net

  # ------------------
  # Logstash 8.18.8
  # ------------------
  logstash:
    image: docker.elastic.co/logstash/logstash:8.18.8
    container_name: textok-logstash
    user: root
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=next5_db
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/lib/mysql-connector-j-8.0.33.jar:/usr/share/logstash/mysql-connector.jar:ro
    ports:
      - "5001:5001"
      - "5044:5044"
    profiles: [ "elk" ]
    depends_on:
      - elasticsearch
    networks:
      - next5-net

volumes:
  mysql_data:

networks:
  next5-net:
    driver: bridge
