server:
  forward-headers-strategy: framework

spring:
  application:
    name: textok-backend

  config:
    activate:
      on-profile: prod

  server:
    address: 0.0.0.0
    port: 8080

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    url: ${SPRING__DATASOURCE__URL}
    username: ${SPRING__DATASOURCE__USERNAME}
    password: ${SPRING__DATASOURCE__PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false

  cache:
    type: redis

  data:
    redis:
      host: ${SPRING__REDIS__HOST}
      port: ${SPRING__REDIS__PORT}
      password: ${SPRING__REDIS__PASSWORD}

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}

  ai:
    openai:
      api-key: ${AI_OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
    huggingface:
      chat:
        api-key: ${AI_HUGGINGFACE_API_KEY}
    vectorstore:
      pinecone:
        api-key: ${PINECONE_API_KEY}
        index-name: ${PINECONE_INDEX_NAME}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_SENDER_EMAIL}
    password: ${GMAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            authorization-grant-type: authorization_code
            redirect-uri: https://api.textok.store/login/oauth2/code/google
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: https://api.textok.store/login/oauth2/code/kakao
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: profile_nickname, profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://api.textok.store/login/oauth2/code/naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET}
  access-exp: 10m
  refresh-exp: 14d

file:
  upload:
    max-size: 10485760

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

springdoc:
  swagger-ui:
    display-request-duration: true
    doc-expansion: none
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

unsplash:
  base-url: https://api.unsplash.com
  access-key: ${UNSPLASH_ACCESS_KEY}

google:
  base-url: https://www.googleapis.com/customsearch/v1
  api-key: ${GOOGLE_API_KEY}
  cx-id: ${GOOGLE_CX_ID}
  cloud:
    credentials:
      json: ${GOOGLE_CLOUD_CREDENTIALS_JSON:}

pixabay:
  base-url: https://pixabay.com
  access-key: ${PIXABAY_ACCESS_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
